site_name: Libspectrum
repo_url: https://github.com/Routybor/libspectrum
repo_name: libspectrum
nav:
  - Home: index.md
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - content.code.copy
  font:
    code: JetBrains Mono
site_dir: docs_generated
watch:
  - pyspectrum
  - examples
plugins:
  - search:
      enabled: true
  - autorefs
  - mkdocs-jupyter:
      include: ["*.ipynb"]
      include_source: True
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: false
            paths: [.]
            docstring_style: sphinx
            show_root_toc_entry: false
            members_order: "source"
            group_by_category: false
            heading_level: 3
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite

nav:
  - "index.md"
  - "API": "reference.md"
  - "Примеры":
      - "Запись спектра": "examples/led_parameters.ipynb"
      - "Пирометр": "examples/pyrometer.ipynb"
      - "Характеристики ламп": "examples/led_parameters.ipynb"
      - "Колориметр": "examples/colorimeter.ipynb"
  - "Документация Пользователя":
      - "Обзор": "user-docs/overview.md"
      - "Уставка библиотеки" : "user-docs/installation.md"
      - "Класс UsbDevice": "user-docs/usb-device.md"
  - "Документация Разработчика":
      - "Среда Разработки": "dev-docs/develop-environment.md"
      - "Архитектурный обзор": "dev-docs/architecture.md"
      - "Платформенные ограничения" : "dev-docs/platform-limitations.md"
      - "Класс UsbDevice": "dev-docs/usb-device.md"
      - "Класс UsbContext": "dev-docs/usb-context.md"
