site_name: Pyspectrum documentation
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
  font:
    code: JetBrains Mono
site_dir: docs_generated
watch:
  - pyspectrum
  - examples
plugins:
  - search:
      enabled: true
  - autorefs
  - mkdocs-jupyter:
      include: ["*.ipynb"]
      include_source: True
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: false
            paths: [.]
#            docstring_style: sphinx
            show_root_toc_entry: false
            members_order: "source"
            group_by_category: false
            heading_level: 3
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.superfences

nav:
  - 'index.md'
  - 'installation.md'
  - 'reference.md'
  - 'Примеры':
      - 'Запись спектра': 'examples/led_parameters.ipynb'
      - 'Пирометр': 'examples/pyrometer.ipynb'
      - 'Характеристики ламп': 'examples/led_parameters.ipynb'
      - 'Колориметр': 'examples/colorimeter.ipynb'
  - 'Документация Разработчика':
      - 'Среда Разработки': 'dev-docs/develop-environment.md'
      - 'Архитектурный обзор': 'dev-docs/architecture.md'