[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.mkdocs]
site_name = "Pyspectrum documentation"
theme = "material"
plugins = ["mkdocstrings", "mkdocs-jupyter"]

[tool.isort]
profile = "black"

[tool.cibuildwheel]
# Setuptools bug causes collision between pypy and cpython artifacts
before-build = "rm -rf {project}/build"